name: 'Lighthouse CI Datadog Action'
description: 'sends Lighthouse metrics to Datadog'
author: 'misogihagi'

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: 'heart'
  color: 'red'

# Define your inputs here.
inputs:
  dd-api-key:
    description:
      'Your Datadog API key. environment value DD_API_KEY is also available.'
    required: false
  dd-app-key:
    description:
      'Your Datadog APP key. environment value DD_APP_KEY is also available.'
    required: false

# Define your outputs here.

runs:
  using: node20
  main: dist/index.js
